name: Destroy branch infrastructure

on:
  pull_request:
    branches:
      - "main"
    types: [closed]
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./

jobs:
  destroy_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select
        run: terraform workspace select dev-${{ github.head_ref }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform switch to default workspace
        run: terraform workspace select default
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace delete
        run: terraform workspace delete dev-${{ github.head_ref }}
        working-directory: ${{ env.WORKING_DIR }}
