name: Terraform validate and format check

on:
  workflow_call: # Makes the workflow reusable

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Step 2: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # Step 3: Initialize Terraform
      - name: Terraform init
        run: terraform init

      # Step 4: Check Terraform format
      - name: Terraform fmt check
        run: terraform fmt -check -recursive
        continue-on-error: false

      # Step 5: Validate Terraform code
      - name: Terraform validate
        run: terraform validate
